-- lua/configs/editortheme.lua

-- vim.opt.termguicolors = true
-- vim.opt.background = "dark" -- Set background to light (or "dark" if preferred)
-- -- vim.cmd("colorscheme zenwritten")

-- require("tokyonight").setup({
-- 	style = "night",
-- 	light_style = "day",
-- 	transparent = false,
-- 	terminal_colors = true,
-- 	styles = {
-- 		comments = { italic = true },
-- 		keywords = { italic = true },
-- 		functions = {},
-- 		variables = {},
-- 		sidebars = "dark",
-- 		floats = "dark",
-- 	},
--
-- 	sidebars = { "qf", "help" },
--
-- 	on_colors = function(colors)
-- 		-- Base colors
-- 		colors.bg = "#1f1f1f"
-- 		colors.bg_dark = "#0a0a0a"
-- 		colors.bg_float = "#1a1a1a"
-- 		colors.bg_highlight = "#1e1e1e"
-- 		colors.bg_popup = "#1a1a1a"
-- 		colors.bg_search = "#3a3a3a"
-- 		colors.bg_sidebar = "#151515"
-- 		colors.bg_statusline = "#1a1a1a"
-- 		colors.bg_visual = "#3a3a3a"
-- 		colors.black = "#000000"
--
-- 		-- Changed all blues to dark violet shades
-- 		colors.blue = "#7f5af0" -- Primary violet
-- 		colors.blue0 = "#5e43a1" -- Darker violet
-- 		colors.blue1 = "#6d5acf" -- Lighter violet
-- 		colors.blue2 = "#5d4dbb" -- Medium violet
-- 		colors.blue5 = "#9370db" -- Soft violet (replaces light blue)
-- 		colors.blue6 = "#b399ff" -- Light violet
-- 		colors.blue7 = "#453a6e" -- Dark violet background
--
-- 		colors.border = "#252525"
-- 		colors.border_highlight = "#3a3a3a"
-- 		colors.comment = "#6a6a6a"
-- 		colors.cyan = "#7dcfff" -- Keeping cyan as is for contrast
-- 		colors.dark3 = "#545c7e"
-- 		colors.dark5 = "#737aa2"
-- 		colors.diff = { add = "#283b4b", change = "#272d43", delete = "#3f2d3d", text = "#394b70" }
-- 		colors.fg = "#d4d4d4"
-- 		colors.fg_dark = "#b0b0b0"
-- 		colors.fg_float = "#d4d4d4"
-- 		colors.fg_gutter = "#4e4e4e"
-- 		colors.fg_sidebar = "#b0b0b0"
-- 		colors.green = "#9ece6a"
-- 		colors.green1 = "#73daca"
-- 		colors.green2 = "#41a6b5"
-- 		colors.hint = "#e0af68"
-- 		colors.info = "#7f5af0" -- Using primary violet for info
-- 		colors.magenta = "#bb9af7"
-- 		colors.magenta2 = "#ff007c"
-- 		colors.orange = "#ff9e64"
-- 		colors.purple = "#9d7cd8"
-- 		colors.red = "#f7768e"
-- 		colors.red1 = "#db4b4b"
-- 		colors.teal = "#1abc9c"
-- 		colors.warning = "#e0af68"
-- 		colors.yellow = "#e0af68"
-- 	end,
--
-- 	on_highlights = function(highlights, colors)
-- 		highlights.Normal = { fg = colors.fg, bg = colors.bg }
-- 		highlights.NormalFloat = { fg = colors.fg_float, bg = colors.bg_float }
-- 		highlights.FloatBorder = { fg = colors.border, bg = colors.bg_float }
-- 		highlights.Comment = { fg = colors.comment, italic = true }
--
-- 		-- Syntax highlights with violet instead of blue
-- 		highlights.Function = { fg = colors.blue1 }
-- 		highlights.Keyword = { fg = colors.blue, italic = true }
-- 		highlights.Identifier = { fg = colors.blue5 }
-- 		highlights.Type = { fg = colors.blue2 }
-- 		highlights.Include = { fg = colors.blue }
-- 		highlights.StorageClass = { fg = colors.blue }
-- 		highlights.Structure = { fg = colors.blue }
-- 		highlights.Typedef = { fg = colors.blue }
--
-- 		highlights.String = { fg = "#b5bd68" }
-- 		highlights.LineNr = { fg = colors.fg_gutter }
-- 		highlights.CursorLineNr = { fg = colors.yellow }
-- 		highlights.Search = { fg = colors.bg, bg = colors.yellow }
-- 		highlights.IncSearch = { fg = colors.bg, bg = colors.orange }
-- 		highlights.CursorLine = { bg = colors.bg_highlight }
-- 		highlights.Visual = { bg = colors.bg_visual }
-- 		highlights.Pmenu = { bg = colors.bg_float }
-- 		highlights.PmenuSel = { bg = colors.bg_search }
-- 		highlights.StatusLine = { bg = colors.bg_statusline }
--
-- 		-- Diagnostic highlights using violet
-- 		highlights.DiagnosticError = { fg = colors.red1 }
-- 		highlights.DiagnosticWarn = { fg = colors.warning }
-- 		highlights.DiagnosticInfo = { fg = colors.blue } -- Using violet for info
-- 		highlights.DiagnosticHint = { fg = colors.hint }
--
-- 		-- LSP highlights
-- 		highlights.LspReferenceText = { bg = colors.blue7 }
-- 		highlights.LspReferenceRead = { bg = colors.blue7 }
-- 		highlights.LspReferenceWrite = { bg = colors.blue7 }
-- 	end,
-- })
--
-- vim.cmd("colorscheme tokyonight-night")
